### ISSUE TITLE
keyring issues in ubntu docker

### ISSUE THREAD

**Issue by nimish-ks** [phasehq/cli#11]
```bash
root@8100edf20c58:/home# phase
usage: phase-cli [-h] [--version] {auth,init,run,secrets,logout,web,keyring} ...

                
        :S@tX88%%t.                   
        ;X;%;@%8X@%;.  Phase-cli               
      ;Xt%;S8:;;t%S    Encrypt the signal, store the noise.               
      ;SXStS@.;t8@: ;. © 2023 Phase Security Inc.               
    ;@:t;S8  ;@.%.;8:  https://phase.dev               
    :X:S%88    S.88t:. https://github.com/phasehq/console                
  :X:%%88     :S:t.t8t                              
.@8X888@88888888X8.%8X8888888X8.S88: 
                ;t;X ;X;    ;tXS:%X;
                :@:8@X..   tXXS%S8    
                ...X:@8S ..X%88X:;     
                  ..@:X88:8Xt8:.       
                    .;%88@S8:XS                       
    

positional arguments:
  {auth,init,run,secrets,logout,web,keyring}
    auth                Authenticate with Phase
    init                Link your local repo to a Phase app environment
    run                 Automatically run and inject environment variables to your application
    secrets             Manage your secrets
    logout              Logout from phase-cli and delete local credentials
    web                 Open the Phase Console in the default web browser
    keyring             Display information about the phase keyring

options:
  -h, --help            show this help message and exit
  --version, -v         show program's version number and exit
root@8100edf20c58:/home# phase init
Traceback (most recent call last):
  File "phase-cli.py", line 425, in <module>
  File "phase-cli.py", line 330, in get_credentials
  File "keyring/core.py", line 55, in get_password
  File "keyring/backends/fail.py", line 25, in get_password
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
[226] Failed to execute script 'phase-cli' due to unhandled exception!
root@8100edf20c58:/home# phase auth
Traceback (most recent call last):
  File "phase-cli.py", line 425, in <module>
  File "phase-cli.py", line 330, in get_credentials
  File "keyring/core.py", line 55, in get_password
  File "keyring/backends/fail.py", line 25, in get_password
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
[228] Failed to execute script 'phase-cli' due to unhandled exception!
root@8100edf20c58:/home# phase auth
Traceback (most recent call last):
  File "phase-cli.py", line 425, in <module>
  File "phase-cli.py", line 330, in get_credentials
  File "keyring/core.py", line 55, in get_password
  File "keyring/backends/fail.py", line 25, in get_password
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
[230] Failed to execute script 'phase-cli' due to unhandled exception!
root@8100edf20c58:/home# phase-cli 
bash: phase-cli: command not found
root@8100edf20c58:/home# phase keyring
Traceback (most recent call last):
  File "phase-cli.py", line 425, in <module>
  File "phase-cli.py", line 330, in get_credentials
  File "keyring/core.py", line 55, in get_password
  File "keyring/backends/fail.py", line 25, in get_password
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
[233] Failed to execute script 'phase-cli' due to unhandled exception!
```

notes: include keyring backend package

**Comment by nimish-ks** [comment]
also on alpine:
```sh
~ # apk add --allow-untrusted phase-1.0.0-r0.apk 
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
(1/1) Installing phase (1.0.0-r0)
Executing busybox-1.36.1-r0.trigger
OK: 21 MiB in 16 packages
~ # phase
usage: phase-cli [-h] [--version]
                 {auth,init,run,secrets,logout,web,keyring} ...

                
        :S@tX88%%t.                   
        ;X;%;@%8X@%;.  Phase-cli               
      ;Xt%;S8:;;t%S    Encrypt the signal, store the noise.               
      ;SXStS@.;t8@: ;. © 2023 Phase Security Inc.               
    ;@:t;S8  ;@.%.;8:  https://phase.dev               
    :X:S%88    S.88t:. https://github.com/phasehq/console                
  :X:%%88     :S:t.t8t                              
.@8X888@88888888X8.%8X8888888X8.S88: 
                ;t;X ;X;    ;tXS:%X;
                :@:8@X..   tXXS%S8    
                ...X:@8S ..X%88X:;     
                  ..@:X88:8Xt8:.       
                    .;%88@S8:XS                       
    

positional arguments:
  {auth,init,run,secrets,logout,web,keyring}
    auth                Authenticate with Phase
    init                Link your local repo to a Phase app environment
    run                 Automatically run and inject environment variables to your application
    secrets             Manage your secrets
    logout              Logout from phase-cli and delete local credentials
    web                 Open the Phase Console in the default web browser
    keyring             Display information about the phase keyring

options:
  -h, --help            show this help message and exit
  --version, -v         show program's version number and exit
~ # phase init
Traceback (most recent call last):
  File "phase-cli.py", line 425, in <module>
  File "phase-cli.py", line 330, in get_credentials
  File "keyring/core.py", line 55, in get_password
  File "keyring/backends/fail.py", line 25, in get_password
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
[14] Failed to execute script 'phase-cli' due to unhandled exception!
~ # phase auth
Traceback (most recent call last):
  File "phase-cli.py", line 425, in <module>
  File "phase-cli.py", line 330, in get_credentials
  File "keyring/core.py", line 55, in get_password
  File "keyring/backends/fail.py", line 25, in get_password
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
[16] Failed to execute script 'phase-cli' due to unhandled exception!
~ # phase keyring
Traceback (most recent call last):
  File "phase-cli.py", line 425, in <module>
  File "phase-cli.py", line 330, in get_credentials
  File "keyring/core.py", line 55, in get_password
  File "keyring/backends/fail.py", line 25, in get_password
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
[18] Failed to execute script 'phase-cli' due to unhandled exception!

```
